version: '3'
services:

  koans-p3:
    image: python_koans
    build: .
    working_dir: /python-koans/python3/
    command: sniffer
    volumes:
      - .:/python-koans

  koans-p2:
    image: python_koans
    working_dir: /python-koans/python2/
    command: sniffer
    volumes:
      - .:/python-koans
